config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  devise_for :users

  resources :categories do
    resources :tasks
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  validates :name, presence: true,
                    uniqueness: true,
                    length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  validates :title, presence: true,
                    uniqueness: true

  validates :content, presence: true,
                      length: { minimum: 10 }

  validates :priority, presence: true  

  validate :priority_cannot_be_in_the_past, on: :create

  def priority_cannot_be_in_the_past
    errors.add(:priority, "date can't be in the past") if priority.present? && priority < Date.today
  end

  def self.get_priority_tasks_for_today
    Task.where(priority: Date.today.beginning_of_day..Date.today.end_of_day).order(priority: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @categories = current_user.categories.all
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build category_params

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
   params.require(:category).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build task_params.merge({user: current_user})
    if @task.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    @task = @category.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to category_path(@category)
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy

    redirect_to category_path(@category)
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :category_id, :priority)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for category, url: url, method: method do |f| %>
  <div class="mb-6">
    <p>
      <label class="form-label inline-block mb-2 text-gray-700"><%= f.label :name, "Category name" %></label>
    <br/>
      <%= f.text_field :name %>
    </p>
  </div>
  <small>
    <% if @category.errors.any? %>
        <% @category.errors.full_messages.each do |message| %>
          <p class="my-5 text-gray-700"><%= message %></p>
        <% end %>
    <% end %>
  </small>
  <button 
    class="px-6 py-2.5 w-full bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
    hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
    active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
    <%= f.submit %>
  </button>
<% end %>

app/views/categories/edit.html.erb
<div class="block p-6 rounded-lg shadow-lg bg-zinc-100 max-w-sm">
  <%= render "form", category: @category, url: category_path(@category), method: :patch  %>
  <div class="flex flex-row mt-8">
    <button class="px-6 py-2.5 w-3/6 mr-1 bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
      hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
      <%= link_to 'Back', category_path(@category) %>
    </button>
    <button>
      <%= button_to 'Delete', category_path(@category), method: :delete,
      class: "px-6 py-2.5 w-3/6 ml-1  bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
      hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
    </button>
  </div>
</div>

app/views/categories/index.html.erb
<div class="flex w-2/4 flex-col justify-center items-center">
  <section class="flex items-center justify-center text-white">
    <% @categories.each do |category| %>
      <button class="px-6 py-2.5 bg-neutral-700 font-medium text-sm leading-tight hover:bg-blue-700
      focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out">
        <%= link_to "#{category.name}", category_path(category) %>
      </button>
    <% end %>
    <button class="px-6 py-2.5 bg-neutral-700 font-medium text-sm leading-tight hover:bg-blue-700
      focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out text-blue-400">
      <%= link_to 'Create new category?', new_category_path %>
    </button>
    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "px-6 py-2.5 bg-neutral-900 font-medium text-sm text-white leading-tight hover:bg-blue-700 focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out text-yellow-500" %>
  </section>
  <div class="flex flex-col">
    <h1 class="text-xl font-medium my-5 text-center text-white">Tasks for today</h1>
    <%= render 'tasks/prio_tasks' %>
  </div>
</div> 

app/views/categories/new.html.erb
<div class="block p-6 rounded-lg shadow-lg bg-zinc-100 max-w-sm">
  <div class="flex flex-col">
    <%= render "form", category: @category, url: categories_path, method: :post %>
    <button class="px-6 py-2.5 mt-3 bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
    hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
    active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"><%= link_to "Back", root_path %></button>
  </div>
</div>

app/views/categories/show.html.erb
<div class="flex flex-col text-white">
  <h1 class="text-center font-medium leading-tight text-3xl my-8 text-blue-400"><%= @category.name %></h1>
  <div class="flex">
    <button 
      class="px-6 py-2.5 bg-neutral-700 font-medium text-sm leading-tight hover:bg-blue-700
      focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out">
      <%= link_to 'Home', root_path %>
    </button>
    <button 
      class="px-6 py-2.5 bg-neutral-700 font-medium text-sm leading-tight hover:bg-blue-700
      focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out">
      <%= link_to 'Edit Category', edit_category_path(@category), class: "text-blue-400" %>
    </button>
    <button 
      class="px-6 py-2.5 bg-neutral-900 font-medium text-sm leading-tight hover:bg-blue-700
      focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out">
      <%= link_to 'Create new task?', new_category_task_path(@category), class: "text-yellow-500" %>
    </button>
  </div>
  <%= render 'tasks/cat_tasks', :category => @category %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="flex flex-col justify-center items-center h-screen w-screen bg-zinc-800">
      <p class="notice text-yellow-500"><%= notice %></p>
      <p class="alert text-red-500 mb-5"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_cat_tasks.html.erb
<% if category.tasks.empty? %>
  <p class="text-center my-8">No current tasks</p>
<% else %>
<% category.tasks.each do |task| %>
    <div class="flex justify-center mt-6">
      <div class="block rounded-lg shadow-lg bg-zinc-100 max-w-sm px-20 text-center">
        <div class="py-3 px-6 border-b text-base text-blue-500 border-gray-300 text-gray-700">
          <%= link_to 'Edit', edit_category_task_path(@category, task) %>
        </div>
        <div class="p-2">
          <h5 class="text-gray-900 text-xl font-medium mb-2"><%= task.title %></h5>
          <p class="text-gray-700 text-base mb-2">
            <%= task.content %>
          </p>
        </div>
        <div class="py-3 px-6 border-t text-xs border-gray-300 text-gray-600">
          <%= task.priority.strftime("%b %d, %y, %l:%M %P") %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for task, url: url, method: method do |f| %>
    <div class="mb-2">
      <div>
        <label class="form-label inline-block mb-2 text-gray-700"><%= f.label :title %></label>
        <br/>
        <%= f.text_field :title %>
      </div>
      <div class="mt-4">
        <label class="form-label inline-block mb-2 text-gray-700"><%= f.label :content, "Description" %></label>
        <br/>
        <%= f.text_field :content %>
      </div>
      <div class="mt-4">
        <label class="form-label inline-block mb-2 text-gray-700"><%= f.label :priority, "Deadline" %></label>
        <br/>
        <%= f.datetime_field :priority %>
      </div>
    </div>
    <small>
      <% if @task.errors.any? %>
        <% @task.errors.full_messages.each do |message| %>
          <p class="my-1 text-gray-700"><%= message %></p>
        <% end %>
      <% end %>
    </small>
    <button 
      class="px-6 w-full py-2.5 mt-5 bg-neutral-700 text-white self-center font-medium text-sm leading-tight shadow-md
      hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
      <%= f.submit %>
    </button>
<% end %>

app/views/tasks/_prio_tasks.html.erb
<% if Task.get_priority_tasks_for_today.length == 0 %>
  <h3 class="text-white text-center">There are no tasks for today</h3>
<% else %>
<% Task.get_priority_tasks_for_today.each do |task| %>
    <div class="flex justify-center my-2">
      <div class="block rounded-lg shadow-lg bg-zinc-100 max-w-sm px-20 text-center">
        <div class="py-2 px-6 border-b border-gray-300 text-gray-700 text-blue-500">
          <%= task.category.name %>
        </div>
        <div class="p-2">
          <h5 class="text-gray-900 text-xl font-medium mb-1"><%= task.title %></h5>
          <p class="text-gray-700 text-base mb-2">
            <%= task.content %>
          </p>
        </div>
        <div class="py-2 px-6 border-t text-xs border-gray-300 text-gray-600">
          <%= task.priority.strftime("%b %d, %y, %l:%M %P") %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<div class="p-6 rounded-lg shadow-lg bg-zinc-100 max-w-sm">
<%= render "form", task: @task, url: category_task_path(@category, @task), method: :patch  %>
 <div class="flex flex-row mt-8">
    <button class="px-6 py-2.5 w-3/6 mr-1 bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
      hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
      <%= link_to 'Back', category_path(@category) %>
    </button>
    <button>
    <%= button_to 'Delete', category_task_path(@category, @task), method: :delete, 
    class: "px-6 py-2.5 w-3/6 ml-1  bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
    hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
    active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
    </button>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="block p-6 rounded-lg shadow-lg bg-zinc-100 max-w-sm">
  <div class="flex flex-col">
    <%= render "form", task: @task, url: category_tasks_path, method: :post %>
    <button class="px-6 py-2.5 mt-3 bg-neutral-700 text-white font-medium text-sm leading-tight shadow-md
    hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
    active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"><%= link_to 'Back', category_path(@category) %></button>
  </div>
</div>